name: deploy-manifests

on:
    push:
        branches:
            - main
        paths:
            - 'infra/k8s-prod/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Authenticate with DigitalOcean
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Config kubectl
              run: doctl kubernetes cluster kubeconfig save mycluster

            - name: Update deployment
              run: kubectl apply -f infra/k8s-prod
