name: deploy-payments

on:
    push:
        branches:
            - main
        paths:
            - 'payments/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to dockerhub
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build image
              run: cd payments && docker build -t huyfst/payments .

            - name: Cache Trivy DB
              uses: actions/cache@v3
              with:
                  path: ~/.cache/trivy
                  key: ${{ runner.os }}-trivy-db

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.28.0
              with:
                  image-ref: 'huyfst/payments'
                  format: 'table'
                  ignore-unfixed: true
                  vuln-type: 'os,library'
                  severity: 'CRITICAL,HIGH,MEDIUM'

            - name: Push to artifact env
              run: docker push huyfst/payments

            - name: Authenticate with DigitalOcean
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Config kubectl
              run: doctl kubernetes cluster kubeconfig save mycluster

            - name: Update deployment
              run: kubectl rollout restart deployment payments-depl -n ingress-nginx
