name: deploy-manifests

on:
    push:
        branches:
            - main
        paths:
            - 'infra/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Authenticate with GCP
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

            # Configure kubectl with GKE
            - name: Configure kubectl
              run: |
                  echo "GKE_CLUSTER_LOCATION is: $GKE_CLUSTER_LOCATION"
              run: |
                  gcloud container clusters get-credentials $GKE_CLUSTER_NAME --location=$GKE_CLUSTER_LOCATION
              env:
                  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
                  GKE_CLUSTER_REGION: ${{ secrets.GKE_CLUSTER_LOCATION }}

            # Update GKE deployment
            - name: Update GKE Deployment
              run: kubectl rollout restart deployment client-depl
