name: deploy-client

on:
    push:
        branches:
            - main
        paths:
            - 'client/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: cd client && docker build -t huyfst/ticketing-client .
            - run: docker push huyfst/ticketing-client
