name: deploy-auth

on:
    push:
        branches:
            - main
        paths:
            - 'auth/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: cd auth && docker build -t huyfst/auth .

            - name: Cache Trivy DB
              uses: actions/cache@v3
              with:
                  path: ~/.cache/trivy
                  key: ${{ runner.os }}-trivy-db

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.28.0
              with:
                  image-ref: 'huyfst/auth'
                  format: 'table'
                  ignore-unfixed: true
                  vuln-type: 'os,library'
                  severity: 'CRITICAL,HIGH,MEDIUM'

            - name: Push to artifact env
              run: docker push huyfst/auth

            - name: Authenticate with GCP
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

            # Configure kubectl with GKE
            - name: Configure kubectl
              run: |
                  gcloud container clusters get-credentials $GKE_CLUSTER_NAME --location $GKE_CLUSTER_LOCATION
              env:
                  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
                  GKE_CLUSTER_REGION: ${{ secrets.GKE_CLUSTER_LOCATION }}

            # Update GKE deployment
            - name: Update GKE Deployment
              run: kubectl rollout restart deployment client-depl
