name: deploy-manifests

on:
    push:
        branches:
            - main
        paths:
            - 'infra/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Authenticate with GCP
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

            - name:
              run: sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin

            # Configure kubectl with GKE
            - name: Configure kubectl
              run: |
                  gcloud container clusters get-credentials $GKE_CLUSTER_NAME --location=asia-southeast1-a
              env:
                  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
