name: deploy-manifests

on:
    push:
        branches:
            - main
        paths:
            - 'infra/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: install the gcloud cli
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ secrets.GOOGLE_PROJECT }}
                  service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
                  install_components: 'gke-gcloud-auth-plugin'
                  export_default_credentials: true

            # Configure kubectl with GKE
            - name: Configure kubectl
              run: |
                  gcloud container clusters get-credentials $GKE_CLUSTER_NAME --location=asia-southeast1-a
              env:
                  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
