name: tests-orders

on:
  push:
      paths:
          - 'orders/**'
      branches:
          - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: cd orders && npm install && npm run test:ci
