name: tests-auth

on:
    push:
        paths:
            - 'auth/**'
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: cd auth && npm install && npm run test:ci

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  args: >
                      -Dsonar.projectBaseDir=auth
