name: tests-client

on:
    pull_request:
        paths:
            - 'client/**'
        branches:
            - dev
    push:
        paths:
            - 'client/**'
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build & Test
              run: cd client && npm install && npm run test:ci

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENT }}
              with:
                  args: >
                      -Dsonar.projectBaseDir=client
