name: tests-expiration

on:
    pull_request:
        paths:
            - 'expiration/**'
        branches:
            - dev
    push:
        paths:
            - 'expiration/**'
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_EXPIRATION }}
              with:
                  args: >
                      -Dsonar.projectBaseDir=expiration
